name: FastAPI Todo App Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Start FastAPI server in background
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: 🧪 Run demo_todo.py test script
        run: python tests/demo_todo.py
